### ISSUE TITLE
Want to modify the page-3-intro section font family and structure

### ISSUE THREAD

**Issue by SAYAN-DAN** [ASHISH26940/toogoodto#15]
In this website  page-3-intro section font family does not look good, I want to modify it and give the actual font that is used in the original website. and the  page-3-intro h1 is not looking good the  page-3-intro align-items is not centred so I fix the issue.

**Comment by ASHISH26940** [comment]
Please provide me a ss of the issue

**Comment by SAYAN-DAN** [comment]
> Please provide me a ss of the issue

Here  is the screenshot, of what I actually solved - 

 
![19208fe6-6e03-4e04-84fd-f8aeff213e5c](https://github.com/ASHISH26940/toogoodto/assets/142710679/447015ed-e2a1-4893-a831-3ec55ae2cadc)

**Comment by ASHISH26940** [comment]
Closed: The issue has been fixed.
