### ISSUE TITLE
adding a hover zoom effect on the "send your won message" button and mouse pointer css needs to be fixed

### ISSUE THREAD

**Issue by deepbeatz** [ASHISH26940/toogoodto#24]
@ASHISH26940 assign me this issue under apertre24

**Comment by ASHISH26940** [comment]
Update the code and share the ss of button here and I am assigning it to you

**Comment by deepbeatz** [comment]
Shouldnt the mentors be assigning the task 1st and then the mentees be doing the changes and giving prs?

**Comment by ASHISH26940** [comment]
Yeah, that's true but we do not know when or how many mentees will be willing to accept the issue and complete it in time.
That's why we are leaving it to the mentees.
If the issues are valid we assign it to those who have raised it.

**Comment by ASHISH26940** [comment]
Issue has been resolved.
