### ISSUE TITLE
Navbar option is not present in mobile device

### ISSUE THREAD

**Issue by rko0211** [ASHISH26940/toogoodto#32]
![Screen Shot 2024-01-07 at 11 23 36](https://github.com/ASHISH26940/toogoodto/assets/97402824/79a3356b-9d70-4b86-9c03-bbe5ba095fac)

In mobile device we are unable to access navbar option . kindly review my issue and assign me under apertre.

**Comment by ASHISH26940** [comment]
Yeah you can continue working on it.

**Comment by ASHISH26940** [comment]
Completed navbar addition for mobile addition
