### ISSUE TITLE
Fix the color ,arrows of the issue 

### ISSUE THREAD

**Issue by ASHISH26940** [ASHISH26940/toogoodto#33]
![image](https://github.com/ASHISH26940/toogoodto/assets/116710038/7eec6b5d-75f6-42ab-ae4a-9040d3792ea5)

**Comment by ASHISH26940** [comment]
Those who are interested solve this issue

**Comment by YooAshu** [comment]
I'm interested

**Comment by ASHISH26940** [comment]
Completed
