### ISSUE TITLE
Want to make a issue template for this repo 

### ISSUE THREAD

**Issue by AnitSarkar123** [ASHISH26940/toogoodto#34]
Assign me under Aperture'24

**Comment by ASHISH26940** [comment]
Yeah sure its a good one actually

**Comment by ASHISH26940** [comment]
Since the issue assigned date of completion has been already crossed I am assign this issues to others.

**Comment by ASHISH26940** [comment]
Those who are interested can comment here 'Assign me'

**Comment by AnitSarkar123** [comment]
PA sorry about that can you give me one day extra.. Ok🥺🥺 tomorrow is tue last day

**Comment by lord-cyclone100** [comment]
@ASHISH26940 pls assign me this task
