### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by lord-cyclone100** [ASHISH26940/toogoodto#37]
Hey @ASHISH26940 I want to create the hamburger menu

Pls assign me

**Comment by ASHISH26940** [comment]
Add a ss or short video which hamburger you are saying for mobile or desktop view

**Comment by lord-cyclone100** [comment]
https://github.com/ASHISH26940/toogoodto/assets/121711381/7dd14b3c-c7ed-42eb-b43d-929a575a6572

**Comment by ASHISH26940** [comment]
Ok you can start contributing

**Comment by ASHISH26940** [comment]
Those who are interested in the hamburger menu of nav bar same as that of the website can write "Assign me "

**Comment by ASHISH26940** [comment]
to this issue of course

**Comment by Sneha123-zudo** [comment]
Assign me under this issue

**Comment by ASHISH26940** [comment]
Whats the progress

**Comment by YooAshu** [comment]
@ASHISH26940 assign me this pls under APERTE

**Comment by ASHISH26940** [comment]
Happy coding!!

**Comment by ASHISH26940** [comment]
Completed
