### ISSUE TITLE
Make a Light and Dark Mode Button

### ISSUE THREAD

**Issue by ASHISH26940** [ASHISH26940/toogoodto#4]
![Dark_mode_sample](https://github.com/ASHISH26940/toogoodto/assets/116710038/7b67005a-9f60-4335-a405-9b90a5208a7b)

**Comment by ASHISH26940** [comment]
Refer to the above for reference

**Comment by Sneha123-zudo** [comment]
Please assign me this issue.

<img width="950" alt="togglebar" src="https://github.com/ASHISH26940/toogoodto/assets/145490348/e559ef22-f3eb-495f-b93d-f69fdbbd2c30">

<img width="939" alt="togglebarlight" src="https://github.com/ASHISH26940/toogoodto/assets/145490348/686ddba8-8ee6-4da9-b4b3-d072baa8fff9">

I had make the light and dark mode button , just some changes are required , i will do it ....please assign me this issue

**Comment by ASHISH26940** [comment]
Completed and merged.
