### ISSUE TITLE
Make the whole website responsive adding mobile view.

### ISSUE THREAD

**Issue by ASHISH26940** [ASHISH26940/toogoodto#41]
# Can make changes to the size of text remove or add animations such that it do not affect the desktop view but looks good in mobile view.

**Comment by rko0211** [comment]
Kindly assign me this one

**Comment by rko0211** [comment]
Kindly assign me this task under apertre24

**Comment by ASHISH26940** [comment]
After completing the new issue I will surely assign this tasks

**Comment by rko0211** [comment]
Kindly assign me this task

**Comment by rko0211** [comment]
Please assign me this task,

**Comment by Sneha123-zudo** [comment]
Assign me this issue

**Comment by ASHISH26940** [comment]
Yeah Sure

**Comment by ASHISH26940** [comment]
Completed
