### ISSUE TITLE
Fixing hamburger menu 

### ISSUE THREAD

**Issue by YooAshu** [ASHISH26940/toogoodto#44]
![Screenshot_20240111_095213](https://github.com/ASHISH26940/toogoodto/assets/95643200/3aa8714f-f7db-4acc-9024-96498fcc7c80)

The current hamburger menu doesn't look good want to fix this

**Comment by ASHISH26940** [comment]
Ok first what changes you want to make. If changes includes adding animations then I will assign this issue to you.

**Comment by YooAshu** [comment]
Yeah , will try to make it like the original website

**Comment by YooAshu** [comment]
@ASHISH26940
