### ISSUE TITLE
Improvement of Footer Design in "toogoodto" Website

### ISSUE THREAD

**Issue by Soumojitshome2023** [ASHISH26940/toogoodto#45]
## Problem:
The current design of the footer on the "toogoodto" website needs improvement for better visual appeal and alignment with the overall website aesthetics.

## Expected Behavior:
The footer should contribute positively to the overall visual experience of the website, maintaining a cohesive and professional appearance.

## Areas of Suggested Improvement:

Visual Harmony: Ensure that the footer design complements the overall design of the website, maintaining visual harmony.

## Steps to Review:
1.Visit the "toogoodto" website.
2. Scroll to the bottom of the webpage to view the footer.

## Current State:
The current state of the footer design does not align with the expected visual standards.

## Screenshot:

![image](https://github.com/ASHISH26940/toogoodto/assets/121761154/2e100d7f-3e51-4645-93bc-59bd6134934a)

**Comment by Soumojitshome2023** [comment]
@ASHISH26940  Please assign me this issue. I want to work on it. Thank You.

**Comment by ASHISH26940** [comment]
Yeah, what you say is true. But this is an open source contribution one can be flexible with design. 

## What you can do instead:

Add animation using **GSAP** or using **CSS** to the existing design. 
Complex animation : Hard label-15 points
Simple animation: Medium label-10 points

## Some Ideas for animations:

Animations based on scroll
Smooth scrolling
Staggering effects

**Comment by ASHISH26940** [comment]
If interested do say complex or simple animation then Assign me

**Comment by Soumojitshome2023** [comment]
pls assign me 'complex'

**Comment by ASHISH26940** [comment]
Happy Coding

**Comment by lord-cyclone100** [comment]
@ASHISH26940 
Please assign me this task. I would give it on scroll animation as well as video background.

**Comment by ASHISH26940** [comment]
Wait @lord-cyclone100 when he cannot do it then I will assign to you

**Comment by ASHISH26940** [comment]
@Soumojitshome2023 whats the progress and whats your discord Id

**Comment by ASHISH26940** [comment]
@Soumojitshome2023 whats progress have you made please respond

**Comment by lord-cyclone100** [comment]
@ASHISH26940 
Pls assign me this task...i have already commented before

**Comment by ASHISH26940** [comment]
@lord-cyclone100 first do the readme then I am assigning it to you

**Comment by rko0211** [comment]
Please assign me this one

**Comment by ASHISH26940** [comment]
@rko0211 this issue has been given to @lord-cyclone100 

You can do another issue

**Comment by ASHISH26940** [comment]
Completed
