### ISSUE TITLE
Button is not responsive

### ISSUE THREAD

**Issue by rko0211** [ASHISH26940/toogoodto#48]
![Screenshot_2024-01-13-03-50-38-391_com android chrome](https://github.com/ASHISH26940/toogoodto/assets/97402824/e9fcc5da-da1e-498e-b5d2-3d8132f77930)

Send your message button is not responsive 

Kindly assign me this task

**Comment by ASHISH26940** [comment]
Sure ...

**Comment by ASHISH26940** [comment]
Completed
