### ISSUE TITLE
Image hover effect can be better

### ISSUE THREAD

**Issue by rko0211** [ASHISH26940/toogoodto#49]

**Comment by ASHISH26940** [comment]
Which image Hover are you taking about do add an screenshot.

**Comment by rko0211** [comment]
![Screenshot from 2024-01-13 22-34-34](https://github.com/ASHISH26940/toogoodto/assets/97402824/44164a90-a4c2-4f2c-8d9e-741546ae08ae)

![Screenshot from 2024-01-13 22-34-29](https://github.com/ASHISH26940/toogoodto/assets/97402824/9e96d039-5aaa-41bc-9848-2258abf4e456)

in dark mode their look can be better from this..

**Comment by ASHISH26940** [comment]
Yeah sure you can start working on it

**Comment by ASHISH26940** [comment]
Completed
