### ISSUE TITLE
Fix the Responsiveness of this section

### ISSUE THREAD

**Issue by ASHISH26940** [ASHISH26940/toogoodto#5]
![Responsivness](https://github.com/ASHISH26940/toogoodto/assets/116710038/155a1735-cef3-4b30-922e-ccbe869848c6)

**Comment by lord-cyclone100** [comment]
Pls assign me this task

**Comment by IndraniSom** [comment]
@lord-cyclone100 best of luck and keep going..

**Comment by rko0211** [comment]
Kindly assign me this one i want to work on this issue

**Comment by rko0211** [comment]
Kindly assign me this task

**Comment by Sneha123-zudo** [comment]
Please assign me this issue

**Comment by ASHISH26940** [comment]
Yeah sure

**Comment by ASHISH26940** [comment]
Completed
