### ISSUE TITLE
add new_Feature : API boxes

### ISSUE THREAD

**Issue by apu52** [ASHISH26940/toogoodto#50]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/ASHISH26940/toogoodto/assets/114172928/ce434dd7-8c9f-4248-a515-30e61c8f8b58)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@ASHISH26940 Please assign me this issue under APERTRE'24

**Comment by ASHISH26940** [comment]
Yes you can start working but do update the code before giving a pr

**Comment by ASHISH26940** [comment]
Completed
