### ISSUE TITLE
Improvement in readme

### ISSUE THREAD

**Issue by lord-cyclone100** [ASHISH26940/toogoodto#62]
The readme can be improved by adding images contribution processes etc....pls assign me this task @ASHISH26940

**Comment by ASHISH26940** [comment]
yeah sure

**Comment by lord-cyclone100** [comment]
@ASHISH26940 have you used any other technology for this project except html, css, js and gsap?

**Comment by ASHISH26940** [comment]
No additional technology, The tech stack used is clearly stated in the project forum

**Comment by ASHISH26940** [comment]
Completed
