### ISSUE TITLE
night mode product hover color issue and hamburger menu mobile issue

### ISSUE THREAD

**Issue by YooAshu** [ASHISH26940/toogoodto#66]
want to change this 

![Screenshot (123)](https://github.com/ASHISH26940/toogoodto/assets/95643200/615eb3d5-2b76-4a71-8174-f36692944e43)

to this

![Screenshot (121)](https://github.com/ASHISH26940/toogoodto/assets/95643200/6a6541c2-1671-4844-8d86-12f40090bbec)

and also fix the issue of mobile view of hamburger

![Screenshot (122)](https://github.com/ASHISH26940/toogoodto/assets/95643200/a6b9a9d1-eb95-444f-b832-5342af30689e)

**Comment by ASHISH26940** [comment]
Happy Coding!!

**Comment by ASHISH26940** [comment]
Completed.
