### ISSUE TITLE
adding Catering Page

### ISSUE THREAD

**Issue by YooAshu** [ASHISH26940/toogoodto#67]
want to add catering page and link those pages
![Screenshot (124)](https://github.com/ASHISH26940/toogoodto/assets/95643200/4e6adaa9-caf2-4de2-8f22-56f0461c706a)

**Comment by ASHISH26940** [comment]
Do the Previous issue then I am assigning you this Issue

**Comment by YooAshu** [comment]
@ASHISH26940 Completed previous issue

**Comment by ASHISH26940** [comment]
Great Issue , as expected .

Try to proceed with the same animation if any but you can be flexible with the design

Go ahead , Happy Coding

**Comment by ASHISH26940** [comment]
Completed
