### ISSUE TITLE
hover effects

### ISSUE THREAD

**Issue by arghadipmanna101** [ASHISH26940/toogoodto#69]
-Will Add hover effects on photos and text.
- Will add hover effects on hamburger icon.

**Comment by ASHISH26940** [comment]
Please specify which section you will be working on

**Comment by ASHISH26940** [comment]
Do send an Screenshot here

**Comment by arghadipmanna101** [comment]
- Will add hover effect in two photos and "OUR IMPACT" para .
![Screenshot 2024-01-18 115915](https://github.com/ASHISH26940/toogoodto/assets/130065095/70e061fa-6eb1-4ab0-ae0d-1eea8ed1d9c2)

- Will add hover effects on hamburger icon and will bold it.
![image](https://github.com/ASHISH26940/toogoodto/assets/130065095/d966a0fe-fea1-4c44-8a72-50e6ac3b35de)

**Comment by ASHISH26940** [comment]
Completed
