### ISSUE TITLE
website performance enhancement

### ISSUE THREAD

**Issue by abhraneel2004** [ASHISH26940/toogoodto#74]
# Update:

- Will increase the loading speed of the website
- Will do the search engine optimization part.

<div align="center">
<h1> Current Scenario</h1>
<img src="https://github.com/ASHISH26940/toogoodto/assets/115551450/d56278c5-fe2a-4d50-ba56-4a3d52662bc5" width="60%">
</div>

**Comment by ASHISH26940** [comment]
Completed
