### ISSUE TITLE
Adding Image overlay

### ISSUE THREAD

**Issue by lord-cyclone100** [ASHISH26940/toogoodto#8]
![Screenshot (313)](https://github.com/ASHISH26940/toogoodto/assets/121711381/dce425f6-806c-461f-93d7-6566f6f7c750)

i would like to add image overlay so that when mouse is hovered over any item, for ex the cook book....a short description about the book is displayed

**Comment by lord-cyclone100** [comment]
Pull request #8

**Comment by lord-cyclone100** [comment]
Image overlay feature added #17

**Comment by ASHISH26940** [comment]
Pull request of issue Image Feature has been added : Image overlay feature added https://github.com/ASHISH26940/toogoodto/pull/17
